// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZRueiu0eBLlcCx4Dvdxy2EwRAeVQO-Ac',
    appId: '1:1017696428184:android:67fe3bfa5f08485d3ef0ed',
    messagingSenderId: '1017696428184',
    projectId: 'apple-disease-20b0b',
    databaseURL: 'https://apple-disease-20b0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apple-disease-20b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVZKDFrLL9nG03uo9DMDa06GMw_tpUO8',
    appId: '1:1017696428184:ios:f55ab3bd82867c333ef0ed',
    messagingSenderId: '1017696428184',
    projectId: 'apple-disease-20b0b',
    databaseURL: 'https://apple-disease-20b0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apple-disease-20b0b.firebasestorage.app',
    androidClientId: '1017696428184-s01lmi0get5jjuaftr1or8dfs96311ie.apps.googleusercontent.com',
    iosClientId: '1017696428184-32ekhbvla83hophr91b9b2mf7tfgphtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.agromind',
  );

}